import type { ServiceSlug } from "./content";

/**
 * Printfix's own work, as published on the five service pages of printfix.co.in.
 * Specs are Printfix's own descriptions (lightly tidied for spelling).
 * Images: public/work/<slug>-<n>.webp (+ -sm.webp at 640w), generated by scripts/prepare-images.py.
 */
export type Project = {
  slug: string;
  name: string;
  service: ServiceSlug;
  /** One-line category shown on cards, e.g. "Magnetic rigid box, Perfumery". */
  kind: string;
  specs: { label: string; value: string }[];
  images: number;
  alt: string;
  client?: string;
};

const P = (
  slug: string, name: string, service: ServiceSlug, kind: string, alt: string, images: number,
  specs: [string, string][], client?: string,
): Project => ({ slug, name, service, kind, alt, images, specs: specs.map(([label, value]) => ({ label, value })), client });

export const projects: Project[] = [
  // ── Rigid boxes
  P("aethara", "Aethara", "rigid-box", "Book-style rigid box, Gifting", "Navy rigid box with an art-nouveau gold foil illustration", 3,
    [["Type", "Rigid box (setup box)"], ["Style", "Hinged lid, book-style opening"], ["Closure", "Hidden magnetic flap"], ["Finish", "Printed, gold foil stamped logo"], ["Use", "Perfume, gifting, apparel, cosmetics"]]),
  P("glide-red", "Glide V2 Red", "rigid-box", "Side-open rigid box, Gaming", "Red rigid box for Glide V2 finger sleeves on red satin", 3,
    [["Type", "Rigid box"], ["Closure", "Side open"], ["Product", "Finger sleeves"], ["Industry", "Gaming"], ["Colour", "Red"]], "Vero Forza"),
  P("birra-attar", "Birra Attar", "rigid-box", "Magnetic rigid box, Perfumery", "Two-tone rigid attar boxes for Birra on burgundy satin", 3,
    [["Type", "Rigid box"], ["Closure", "Magnetic"], ["Product", "Attar"], ["Industry", "Perfumery"]], "Birra Fragrances"),
  P("glide-yellow", "Glide Yellow", "rigid-box", "Side-open rigid box, Gaming", "Yellow rigid box with a printed doodle pattern on black satin and pearls", 3,
    [["Type", "Rigid box"], ["Closure", "Side open"], ["Product", "Finger sleeves"], ["Industry", "Gaming"], ["Colour", "Yellow"]], "Vero Forza"),
  P("glide-pro", "Glide Pro V2", "rigid-box", "Side-open rigid box, Gaming", "Matte black Glide Pro rigid box on a walnut desk", 4,
    [["Type", "Rigid box"], ["Closure", "Side open"], ["Product", "Finger sleeves"], ["Industry", "Gaming"], ["Colour", "Matte black"]], "Vero Forza"),
  P("vero-forza-magnetic", "Vero Forza × Doodle", "rigid-box", "Magnetic rigid box, Gaming", "Black magnetic rigid box with tone-on-tone doodle print and gold emblems", 3,
    [["Type", "Rigid box"], ["Closure", "Magnetic"], ["Product", "Finger sleeves"], ["Industry", "Gaming"], ["Colour", "Black"]], "Vero Forza"),
  P("olivia-leigh", "Olivia Leigh", "rigid-box", "Book-style rigid box, Gifting", "Burgundy book-style rigid boxes with gold foil Olivia Leigh logo", 3,
    [["Type", "Rigid box (setup box)"], ["Style", "Hinged lid, book-style opening"], ["Closure", "Hidden magnetic flap"], ["Finish", "Printed, gold foil stamped logo"], ["Use", "Perfume, gifting, apparel, cosmetics"]]),
  P("af-abaya", "A&F Abaya", "rigid-box", "Book-style rigid box, Fashion", "Burgundy A&F Abaya rigid box with a printed rose border", 4,
    [["Type", "Rigid box (setup box)"], ["Style", "Hinged lid, book-style opening"], ["Closure", "Hidden magnetic flap"], ["Finish", "Printed, gold foil stamped logo"], ["Use", "Abaya & clothing brand"]]),
  P("ruixuecui", "Ruixuecui", "rigid-box", "Book-style rigid box, Brand kits", "Cream rigid box with blind-embossed lettering and light-gold foil", 4,
    [["Type", "Rigid box (setup box)"], ["Style", "Hinged lid, book-style opening"], ["Closure", "Hidden magnetic flap"], ["Finish", "Blind embossing, light-gold foil stamping, matte / soft-touch lamination"], ["Use", "Premium brand kits"]]),
  P("velina", "Velina", "rigid-box", "Shoulder-neck rigid box, Perfumery", "Green shoulder-neck rigid perfume box with gold foil florals", 4,
    [["Type", "Rigid shoulder-neck box (modified cube)"], ["Style", "Lift-off lid, luxury reveal"], ["Closure", "Friction-fit hinged box (jewellery style)"], ["Finish", "Gold foil stamping, matte / textured, smooth interior lining"], ["Use", "Premium perfume brand"]]),

  // ── Corrugated boxes
  P("le-rose", "Le Rose", "corrugated-box", "Printed mailer, Beauty subscription", "Blue corrugated mailer with white-ink leaves and Le Rose lettering", 3,
    [["Type", "Corrugated box"], ["Style", "3-ply corrugated board (E- or B-flute)"], ["Closure", "Roll end tuck front (RETF)"], ["Finish", "Offset printed outer liner, matte look, white-ink floral design and typography"], ["Use", "Beauty and skincare subscription box"]]),
  P("gift-set", "Ryabina Gift Set", "corrugated-box", "Corrugated gift box, Gifting", "Kraft corrugated gift set boxes stacked in rows", 4,
    [["Type", "Corrugated box"], ["Closure", "Roll end tuck front"], ["Product", "Gifting"]]),
  P("muse-mailer", "Muse Mailer", "corrugated-box", "Kraft mailer, Fashion & apparel", "Kraft corrugated mailer with a printed inner flap", 2,
    [["Type", "Corrugated box"], ["Closure", "Roll end tuck front"], ["Product", "Fashion & apparels"]]),
  P("rhode", "rhode", "corrugated-box", "Mailer box, Skincare", "Off-white corrugated mailer with a single-colour rhode logo", 4,
    [["Type", "Corrugated box"], ["Style", "Corrugated (E- or F-flute)"], ["Closure", "Roll end tuck front (RETF)"], ["Finish", "Matte finish in cream / off-white, minimalist single-colour branding"], ["Use", "Cosmetics & skincare"]]),
  P("mavie", "Mavie", "corrugated-box", "Printed mailer, Clothing brand", "Pink corrugated mailer box with Mavie wordmark", 3,
    [["Type", "Corrugated box"], ["Closure", "Roll end tuck front"], ["Industry", "Fashion & apparels"], ["Product", "Clothing brand"]]),
  P("leafcraft", "Leafcraft", "corrugated-box", "Mailer box, Apparel & accessories", "Sage green corrugated mailer with a printed inner lid", 3,
    [["Type", "Corrugated box"], ["Style", "Mailer box"], ["Closure", "Roll end tuck front"], ["Finish", "Matte lamination, spot UV, offset printing in a muted green"], ["Use", "Apparel & accessories"]]),
  P("cacau-spa", "Cacau Spa", "corrugated-box", "Lid & base box, Skincare", "Black lid-and-base boxes printed with copper cocoa leaves", 3,
    [["Type", "Corrugated box"], ["Style", "Rigid lid & base box"], ["Finish", "Matte lamination, spot UV / embossed, white-ink logo"], ["Use", "Premium skincare / spa products"]]),
  P("nzuri", "Nzuri", "corrugated-box", "Tuck-top box, Hair care", "Deep green mailer with gold foil line portrait", 3,
    [["Type", "Corrugated box"], ["Style", "Tuck top box"], ["Closure", "Roll end tuck front"], ["Finish", "Matte lamination, gold foil stamping, dark green Pantone"], ["Use", "Beauty & hair care kits"]]),
  P("kraft-two-piece", "Kraft Two-Piece", "corrugated-box", "Two-piece box, E-commerce", "Kraft two-piece box with a small black printed logo", 3,
    [["Type", "Corrugated box"], ["Style", "Two-piece box"], ["Closure", "Lift-off lid"], ["Finish", "Matte finish, printed logo in black ink"], ["Use", "E-commerce packaging"]]),
  P("pastel-gift", "Pastel Gift Box", "corrugated-box", "Base box, Premium gifting", "Pastel mint box with gold foil borders", 4,
    [["Type", "Corrugated box"], ["Style", "Base box"], ["Closure", "Lift-off lid"], ["Finish", "Matte lamination, pastel mint offset printing, gold foil logo and borders"], ["Use", "Premium gifting"]]),
  P("cbd-mailer", "Calm Relief", "corrugated-box", "Kraft mailer, E-commerce", "Kraft tuck-top mailer printed with a brown pattern", 3,
    [["Type", "Corrugated box"], ["Style", "Tuck top mailer box"], ["Closure", "Roll end tuck front"], ["Finish", "Matte finish, digital printing on kraft"], ["Use", "E-commerce"]]),
  P("mocha-mailer", "Mocha", "corrugated-box", "Kraft mailer, E-commerce", "Kraft tuck-top mailer printed in white", 3,
    [["Type", "Corrugated box"], ["Style", "Tuck top mailer box"], ["Closure", "Roll end tuck front"], ["Finish", "Matte finish, digital printing on kraft"], ["Use", "E-commerce"]]),

  // ── Product boxes
  P("dr-balwi", "Dr. Balwi", "product-box", "Tuck-end carton, Hair treatment", "Purple and white hair treatment cartons", 3,
    [["Type", "Product box"], ["Closure", "Tuck-in flap (straight tuck)"], ["Finish", "Matte lamination & spot UV"], ["Use", "Hair treatment"]]),
  P("jane-roe", "Jane Roe", "product-box", "Tuck-end carton, Skincare", "Teal moisturising spray carton with gold-effect text", 4,
    [["Type", "Product box"], ["Closure", "Tuck-in flap (straight tuck)"], ["Finish", "Matte lamination, spot UV, metallic foil-effect gold text"], ["Use", "Moisturising spray"]]),
  P("vivo-organics", "Vivo Organics", "product-box", "Tuck-end carton, Cosmetics", "White and pink rosehip oil carton with dropper bottle", 3,
    [["Type", "Product box"], ["Closure", "Tuck-in flap (straight tuck)"], ["Finish", "Matte lamination, clean minimal typography"], ["Use", "Cosmetics"]]),
  P("luv-cbd", "Luv", "product-box", "Tuck-end carton, Cosmetics", "Deep green carton with gold foil botanical illustration", 3,
    [["Type", "Product box"], ["Closure", "Tuck-in flap (straight tuck)"], ["Finish", "Soft matte lamination, gold foil stamping, deep green solid colour"], ["Use", "Cosmetics"]]),
  P("lavender-soap", "Lavender Soap", "product-box", "Tuck-end carton, Skincare", "Pink and lavender printed soap cartons", 3,
    [["Type", "Product box"], ["Closure", "Tuck-in flap (straight tuck)"], ["Finish", "Gloss lamination, spot UV, high-quality offset printing"], ["Use", "Skincare"]]),
  P("colact", "Colact", "product-box", "Tuck-end carton, Medicine", "White and purple printed medicine carton", 3,
    [["Type", "Product box"], ["Closure", "Tuck-in flap (straight tuck)"], ["Finish", "Offset printed (high-quality graphics), matte or gloss coating"], ["Use", "Medicine box"]]),
  P("sufr-glow", "SUFR K-Glow", "product-box", "Gift carton, Skincare", "Orange sheet-mask gift carton open to show three sachets", 4,
    [["Type", "Product box"], ["Finish", "Matte lamination, spot UV, foil stamping, high-quality offset printing"], ["Use", "Skincare"]]),
  P("antheara", "Anthēara", "product-box", "Tuck-end carton, Body care", "Dark brown body scrub cartons", 4,
    [["Type", "Product box"], ["Closure", "Tuck-in flap (straight tuck)"], ["Finish", "Matte lamination, spot UV, foil, high-quality offset printing"], ["Use", "Skincare"]]),
  P("hestia", "Hestia", "product-box", "Supplement carton, Health", "Illustrated supplement cartons on a wooden table", 3,
    [["Type", "Product box"], ["Closure", "Roll end tuck front"], ["Product", "Medicine"], ["Industry", "Health & beauty"]]),
  P("arctic", "Arctic", "product-box", "Tuck-end carton, Gaming", "Black Arctic cartons with white line graphics on marble", 4,
    [["Type", "Product box"], ["Closure", "Roll end tuck front"], ["Product", "Finger sleeves"], ["Industry", "Gaming"]], "Vero Forza"),
  P("sage-bloom", "Sage & Bloom", "product-box", "Folding box, Skincare", "White and blush skincare box open around a cream jar", 4,
    [["Type", "Product box"], ["Finish", "Matte lamination, spot UV, foil, high-quality offset printing"], ["Use", "Skincare"]]),

  // ── Paper bags
  P("b-boutique", "B Boutique", "paper-bags", "Rigid laminated bag, Boutique", "Ivory paper bag with black ribbon handles and a monogram", 4,
    [["Type", "Paper bag"], ["Style", "Rigid laminated paper bag"], ["Handles", "Ribbon (fabric)"], ["Finish", "Art paper / ivory board, soft-touch lamination, single-colour logo"], ["Use", "Boutique / premium presentation"]]),
  P("still", "Still", "paper-bags", "Luxury handle bag, Boutique", "Dark brown paper bag with ribbon handles and pink lettering", 3,
    [["Type", "Paper bag"], ["Style", "Luxury rope handle paper bag"], ["Handles", "Ribbon (fabric)"], ["Finish", "Matte lamination, velvety feel, high-end logo print"], ["Use", "Boutique shopping bag"]]),
  P("nuda", "nuda.", "paper-bags", "Shopping bag, Fashion", "White paper bag with red satin ribbon handles", 3,
    [["Type", "Paper bag"], ["Style", "Luxury paper shopping bag"], ["Handles", "Satin red ribbon"], ["Finish", "Matte lamination, spot UV on logo"], ["Use", "Fashion brands"]]),
  P("lani-bespoke", "Lani Bespoke", "paper-bags", "Retail bag, Clothing", "Black retail bag with geometric pattern base and cord handles", 3,
    [["Type", "Paper bag"], ["Style", "Luxury retail bag"], ["Handles", "Cotton-look cord"], ["Finish", "Matte lamination, spot UV logo, offset-printed geometric pattern"], ["Use", "Clothing brands"]]),
  P("zealot", "Zealot", "paper-bags", "Euro tote, Corporate", "Black euro tote bag with tonal pattern and ribbon handles", 3,
    [["Type", "Paper bag"], ["Style", "Euro tote"], ["Handles", "Fabric / ribbon"], ["Finish", "Matte lamination, embossed textured pattern"], ["Use", "Corporate branding & events"]]),
  P("moda", "Moda Collection", "paper-bags", "Laminated bag, Premium retail", "Deep red paper bag with gold emblem and cord handles", 3,
    [["Type", "Paper bag"], ["Style", "Luxury laminated paper"], ["Finish", "Matte lamination, emboss / deboss pattern, offset printing"], ["Use", "Premium product packaging"]]),
  P("quynh-nga", "Quynh Nga", "paper-bags", "Euro tote, Clothing", "Black bag with gold shimmer pattern and a monogram", 3,
    [["Type", "Paper bag"], ["Style", "Euro tote paper bag"], ["Handles", "Cotton rope"], ["Finish", "Matte lamination, black base with gold foil / UV design"], ["Use", "Clothing brands"]]),
  P("paloma", "Paloma", "paper-bags", "Carrier bag, Boutique retail", "Navy paper bag with tonal bird pattern and gold Paloma lettering", 4,
    [["Type", "Paper bag"], ["Style", "Premium paper carrier bag"], ["Handles", "Satin ribbon"], ["Finish", "Matte lamination, gold foil stamping, spot UV on design elements"], ["Use", "Boutique retail"]]),
  P("origami-kraft", "Origami Kraft Bag", "paper-bags", "Kraft bag, Food & beverage", "Kraft paper bag with a printed restaurant logo", 3,
    [["Type", "Paper bag"], ["Style", "Kraft paper bag"], ["Handles", "Cotton rope"], ["Finish", "Matte lamination, offset printing (text & logo)"], ["Use", "Food & beverage"]]),

  P("chilis-kraft", "Chili's Kraft Bag", "paper-bags", "Kraft bag, Food & beverage", "Kraft paper delivery bag printed in red and green with rope handles", 4,
    [["Type", "Paper bag"], ["Style", "Kraft paper bag"], ["Handles", "Cotton rope"], ["Finish", "Matte lamination, offset printing (text & logo)"], ["Use", "Food & beverage"]]),
  // ── Books / publishing
  P("signature-dishes", "Signature Dishes", "books-publishing", "Hardcover cookbook", "Black hardcover cookbook next to an open recipe spread", 2,
    [["Type", "Premium cookbook"], ["Size", "A4 closed"], ["Binding", "Hardbound, case binding"], ["Finish", "Matte laminated hardcover, 130-170 GSM art paper"]]),
  P("deeniyat-workbook", "Deeniyat Primary Workbook", "books-publishing", "Educational workbook", "Blue and green workbook cover on a marble plinth", 2,
    [["Type", "Educational workbook"], ["Size", "A5 slim"], ["Binding", "Perfect binding"], ["Finish", "Matte lamination, spot UV on logo, 250-300 GSM art card cover"], ["Use", "School education"]], "Deeniyat"),
  P("deeniyat-amma", "Deeniyat Juz ʿAmma", "books-publishing", "Hardcover educational book", "Blue hardcover book with a gold foil emblem", 3,
    [["Type", "Islamic educational book"], ["Size", "Demy / Crown 1/8"], ["Binding", "Strong gally binding"], ["Finish", "Matte finish, gold foil on logo, 70-80 GSM matte paper"], ["Use", "Madrasas & schools"]], "Deeniyat"),
  P("corporate-brochure", "Corporate Brochure", "books-publishing", "Saddle-stitched brochure", "Grey corporate brochure with a large numeral cover", 3,
    [["Type", "Corporate brochure"], ["Size", "A4 or custom square"], ["Binding", "Saddle stitch (centre pin)"], ["Finish", "Matte lamination, neutral palette"], ["Use", "Business marketing"]]),
  P("technical-brochure", "Technical Brochures", "books-publishing", "Technical catalogue", "Stacked technical brochures with bold numeral covers", 4,
    [["Type", "Technical brochure"], ["Size", "A4 or custom square"], ["Binding", "Saddle stitch"], ["Finish", "Soft-touch matte lamination, spot UV on titles"], ["Use", "Architect / builder reference"]]),
  P("deeniyat-course", "Deeniyat Course Books", "books-publishing", "Educational series", "Blue and pink course books with minaret silhouettes", 4,
    [["Type", "Islamic educational book"], ["Binding", "Strong gally binding"], ["Finish", "Matte finish, gold foiling on logo"], ["Use", "Madrasas & schools"]], "Deeniyat"),
  P("deeniyat-daily", "Deeniyat 5 Minute Madrasa", "books-publishing", "Hardcover self-learning book", "Brown hardcover book with a blind debossed mosque design", 4,
    [["Type", "Islamic self-learning book"], ["Size", "A5 or custom"], ["Finish", "Matte laminated cover, blind deboss, 70-80 GSM matte paper"], ["Use", "Daily Islamic practice"]], "Deeniyat"),
];

export const img = (slug: string, n = 1, sm = false) => `/work/${slug}-${n}${sm ? "-sm" : ""}.webp`;
export const bySlug = (slug: string) => projects.find((p) => p.slug === slug)!;
export const forService = (s: ServiceSlug) => projects.filter((p) => p.service === s);
/** Projects whose own spec names offset printing. */
export const isOffset = (p: Project) => p.specs.some((s) => /offset/i.test(s.value));
export const offsetProjects = () => projects.filter(isOffset);

/** Homepage selection: varied categories, strongest photography. */
export const selectedWork = ["af-abaya", "nuda", "nzuri", "deeniyat-amma", "birra-attar", "luv-cbd"];
export const featured = "ruixuecui";

/** Richer case-study layout for the strongest, most fully specified projects. */
export const caseStudies = ["glide-red", "aethara", "ruixuecui", "nzuri", "paloma", "deeniyat-amma"];
